import {
  Briefcase,
  Plane,
  Utensils,
  Monitor,
  Megaphone,
  ShoppingCart,
  Home,
  Car,
  Zap,
  Heart,
  GraduationCap,
  Coffee,
  Wifi,
  Shirt,
  User,
  BookOpen,
  Music,
  Dumbbell,
  Stethoscope,
  Truck,
  Sparkles,
  TrendingUp,
  PiggyBank,
  MoreHorizontal,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  plane: Plane,
  utensils: Utensils,
  monitor: Monitor,
  megaphone: Megaphone,
  'shopping-bag': ShoppingCart,
  shopping: ShoppingCart,
  home: Home,
  housing: Home,
  car: Car,
  transport: Car,
  zap: Zap,
  utilities: Zap,
  heart: Heart,
  health: Heart,
  book: GraduationCap,
  education: GraduationCap,
  coffee: Coffee,
  subscriptions: Coffee,
  wifi: Wifi,
  internet: Wifi,
  shirt: Shirt,
  clothing: Shirt,
  user: User,
  personal: User,
  groceries: ShoppingCart,
  'books': BookOpen,
  music: Music,
  fitness: Dumbbell,
  gym: Dumbbell,
  medical: Stethoscope,
  delivery: Truck,
  'trending-up': TrendingUp,
  'piggy-bank': PiggyBank,
  misc: Sparkles,
}

export function getCategoryIcon(name?: string | null): LucideIcon {
  if (name && name in iconMap) return iconMap[name]
  return MoreHorizontal
}
